alter table NEWTASK_INVOICE_FILE_DESCRIPTOR_LINK add constraint FK_INVFILDES_INVOICE foreign key (INVOICE_ID) references NEWTASK_INVOICE(ID);
alter table NEWTASK_INVOICE_FILE_DESCRIPTOR_LINK add constraint FK_INVFILDES_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
