create table NEWTASK_SERVICE_COMPLETION_CERTIFICATE_STAGE_LINK (
    SERVICE_COMPLETION_CERTIFICATE_ID varchar(36) not null,
    STAGE_ID varchar(36) not null,
    primary key (SERVICE_COMPLETION_CERTIFICATE_ID, STAGE_ID)
);
