alter table NEWTASK_ORGANIZATION add constraint FK_NEWTASK_ORGANIZATION_CONTRACT foreign key (CONTRACT_ID) references NEWTASK_CONTRACT(ID);
create index IDX_NEWTASK_ORGANIZATION_CONTRACT on NEWTASK_ORGANIZATION (CONTRACT_ID);
