alter table NEWTASK_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CONFILDES_CONTRACT foreign key (CONTRACT_ID) references NEWTASK_CONTRACT(ID);
alter table NEWTASK_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CONFILDES_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
